from __future__ import annotations
from datetime import datetime
from pathlib import Path
import json
from .models import PRDraft, PRStatus
from .repository_validation import RepositoryValidation


MEMORY_DIR = Path(__file__).parent.parent / "memory" / "repository_automation"


class PRGenerator:
    def __init__(self):
        self._prs_path = MEMORY_DIR / "prs.json"
        self._validator = RepositoryValidation()
        MEMORY_DIR.mkdir(parents=True, exist_ok=True)

    def _load(self) -> list[dict]:
        if not self._prs_path.exists():
            return []
        try:
            return json.loads(self._prs_path.read_text())
        except Exception:
            return []

    def _save(self, data: list[dict]) -> None:
        self._prs_path.write_text(json.dumps(data, indent=2, default=str))

    def generate_pr_draft(
        self,
        project_id: str,
        branch_id: str,
        title: str,
        description: str,
        changes: list[dict],
        labels: list[str] | None = None,
        reviewers: list[str] | None = None,
    ) -> tuple[PRDraft | None, str]:
        valid, issues = self._validator.validate_pr_metadata(title, description)
        if not valid:
            return None, "; ".join(issues)

        files_changed = []
        for c in changes:
            files_changed.extend(c.get("files_affected", []))
        files_changed = list(set(files_changed))

        changes_summary = self._build_changes_summary(changes, files_changed)

        draft = PRDraft(
            project_id=project_id,
            branch_id=branch_id,
            title=title,
            description=description,
            changes_summary=changes_summary,
            files_changed=files_changed,
            labels=labels or ["ai-generated", "needs-review"],
            reviewers=reviewers or [],
        )
        prs = self._load()
        prs.append(draft.model_dump())
        self._save(prs)
        return draft, "generated"

    def _build_changes_summary(self, changes: list[dict], files: list[str]) -> str:
        lines = ["## Summary of Changes\n"]
        for c in changes:
            lines.append(f"- **{c.get('change_type', 'change')}**: {c.get('description', '')}")
        lines.append(f"\n**Files affected ({len(files)}):**")
        for f in files[:20]:
            lines.append(f"  - `{f}`")
        if len(files) > 20:
            lines.append(f"  - ... and {len(files) - 20} more")
        return "\n".join(lines)

    def generate_markdown_body(self, pr: PRDraft | dict) -> str:
        if isinstance(pr, PRDraft):
            pr = pr.model_dump()
        body = f"""## {pr.get('title', 'AI-Generated PR')}

{pr.get('description', '')}

---

{pr.get('changes_summary', '')}

---

> **⚠️ AI-Generated PR** — Review required before merge. No auto-merge enabled.
> Generated by MIFTEH AI OS at {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
"""
        return body

    def list_prs(self, project_id: str | None = None, status: str | None = None) -> list[dict]:
        prs = self._load()
        if project_id:
            prs = [p for p in prs if p.get("project_id") == project_id]
        if status:
            prs = [p for p in prs if p.get("status") == status]
        return prs

    def get_pr(self, pr_id: str) -> dict | None:
        for p in self._load():
            if p["id"] == pr_id:
                return p
        return None

    def update_pr_status(self, pr_id: str, status: PRStatus) -> bool:
        prs = self._load()
        for p in prs:
            if p["id"] == pr_id:
                p["status"] = status.value if hasattr(status, "value") else status
                p["updated_at"] = datetime.utcnow().isoformat()
                self._save(prs)
                return True
        return False
