from __future__ import annotations
import base64
import json
from datetime import datetime
from pathlib import Path
import httpx

MEMORY_DIR = Path(__file__).parent.parent / "memory" / "github"
MEMORY_DIR.mkdir(parents=True, exist_ok=True)
_PR_LOG_PATH = MEMORY_DIR / "created_prs.json"

# Repo mapping — loaded from config
REPO_MAP = {
    "yallaplays": "Zakoosh/Yallaplays",
    "fionera": "Zakoosh/fionera",
    "mifteh": "Zakoosh/mifteh",
}

GITHUB_API = "https://api.github.com"
HEADERS_BASE = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


def _load_pr_log() -> list[dict]:
    if not _PR_LOG_PATH.exists():
        return []
    try:
        return json.loads(_PR_LOG_PATH.read_text())
    except Exception:
        return []


def _save_pr_log(data: list[dict]) -> None:
    _PR_LOG_PATH.write_text(json.dumps(data, indent=2, default=str))


class GitHubPRService:
    """Creates real draft PRs on GitHub from PR-ready output JSON files.

    Safety: PRs are always created as drafts. No auto-merge. No auto-deploy.
    """

    def __init__(self, token: str | None = None):
        from ..core.config import get_config
        cfg = get_config()
        self._token = token or cfg.github_token
        self._yp_repo = getattr(cfg, "github_repo_yallaplays", None) or REPO_MAP["yallaplays"]
        self._fi_repo = getattr(cfg, "github_repo_fionera", None) or REPO_MAP["fionera"]
        self._mi_repo = getattr(cfg, "github_repo_mifteh", None) or REPO_MAP["mifteh"]

    def _headers(self) -> dict:
        return {**HEADERS_BASE, "Authorization": f"Bearer {self._token}"}

    def _repo(self, project: str) -> str:
        if project == "yallaplays":
            return self._yp_repo
        if project == "fionera":
            return self._fi_repo
        return self._mi_repo

    async def _get_default_branch_sha(self, client: httpx.AsyncClient, repo: str, branch: str = "main") -> str | None:
        r = await client.get(f"{GITHUB_API}/repos/{repo}/git/refs/heads/{branch}", headers=self._headers())
        if r.status_code == 200:
            return r.json()["object"]["sha"]
        return None

    async def _create_branch(self, client: httpx.AsyncClient, repo: str, branch_name: str, base_sha: str) -> bool:
        r = await client.post(
            f"{GITHUB_API}/repos/{repo}/git/refs",
            headers=self._headers(),
            json={"ref": f"refs/heads/{branch_name}", "sha": base_sha},
        )
        return r.status_code in (200, 201, 422)  # 422 = branch already exists

    async def _upsert_file(
        self, client: httpx.AsyncClient, repo: str, branch: str, file_path: str, content: str, message: str
    ) -> bool:
        encoded = base64.b64encode(content.encode()).decode()
        # Check if file exists to get its SHA
        existing_sha = None
        r = await client.get(
            f"{GITHUB_API}/repos/{repo}/contents/{file_path}",
            headers=self._headers(),
            params={"ref": branch},
        )
        if r.status_code == 200:
            existing_sha = r.json().get("sha")

        body: dict = {
            "message": message,
            "content": encoded,
            "branch": branch,
        }
        if existing_sha:
            body["sha"] = existing_sha

        r = await client.put(
            f"{GITHUB_API}/repos/{repo}/contents/{file_path}",
            headers=self._headers(),
            json=body,
        )
        return r.status_code in (200, 201)

    async def _create_draft_pr(
        self,
        client: httpx.AsyncClient,
        repo: str,
        branch: str,
        base: str,
        title: str,
        body: str,
    ) -> dict | None:
        r = await client.post(
            f"{GITHUB_API}/repos/{repo}/pulls",
            headers=self._headers(),
            json={
                "title": title,
                "body": body,
                "head": branch,
                "base": base,
                "draft": True,
            },
        )
        if r.status_code in (200, 201):
            return r.json()
        return None

    def _build_pr_body(self, output: dict, files_committed: list[str]) -> str:
        safety = output.get("safety", {})
        return f"""## {output.get('suggested_title', '[AI] Generated Improvement')}

{output.get('suggested_description', '')}

---

## Files Changed ({len(files_committed)})
{chr(10).join(f'- `{f}`' for f in files_committed)}

---

## Safety Summary
| Constraint | Status |
|---|---|
| Auto-merge | ❌ Disabled |
| Auto-deploy | ❌ Disabled |
| Human review required | ✅ Required |
| Rollback available | ✅ {'Yes' if safety.get('rollback_available', True) else 'No'} |
| Risk level | `{safety.get('risk_level', 'low')}` |

---

> 🤖 **Generated by MIFTEH AI OS** — `yallaplays.com/admin/os`
> Output ID: `{output.get('output_id', '')}` · Project: `{output.get('project', '')}` · Type: `{output.get('output_type', '')}`
> Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
>
> ⚠️ **Review required before merge. Never auto-merged.**
"""

    async def create_pr_from_output(self, output_json_path: Path | str) -> dict:
        """Create a real GitHub draft PR from a PR-ready output JSON file."""
        if not self._token:
            return {"success": False, "error": "GITHUB_TOKEN not configured"}

        try:
            output = json.loads(Path(output_json_path).read_text())
        except Exception as e:
            return {"success": False, "error": f"Cannot read output file: {e}"}

        project = output.get("project", "")
        repo = self._repo(project)
        branch_name = output.get("suggested_branch", f"ai/improvement/{output.get('output_id', 'unknown')[:8]}")
        title = output.get("suggested_title", "[AI] Generated Improvement")
        files = output.get("files", [])

        if not files:
            return {"success": False, "error": "No files in output to commit"}

        async with httpx.AsyncClient(timeout=30) as client:
            # Get base branch SHA
            base_sha = await self._get_default_branch_sha(client, repo)
            if not base_sha:
                return {"success": False, "error": f"Cannot get main branch SHA for {repo}"}

            # Create branch
            await self._create_branch(client, repo, branch_name, base_sha)

            # Commit files
            files_committed = []
            for f in files:
                file_path = f.get("path", "")
                content = f.get("content") or f.get("description", "")
                if not content:
                    content = f"# AI-generated: {file_path}"
                if not file_path:
                    continue
                commit_msg = f"[AI OS] {f.get('description', f'Update {file_path}')}"
                ok = await self._upsert_file(client, repo, branch_name, file_path, content, commit_msg)
                if ok:
                    files_committed.append(file_path)

            if not files_committed:
                return {"success": False, "error": "No files were successfully committed"}

            # Create draft PR
            pr_body = self._build_pr_body(output, files_committed)
            pr_data = await self._create_draft_pr(client, repo, branch_name, "main", title, pr_body)

            if not pr_data:
                return {"success": False, "error": "Failed to create PR"}

            result = {
                "success": True,
                "pr_url": pr_data["html_url"],
                "pr_number": pr_data["number"],
                "pr_title": pr_data["title"],
                "branch": branch_name,
                "repo": repo,
                "files_committed": files_committed,
                "draft": True,
                "auto_merge": False,
                "created_at": datetime.utcnow().isoformat(),
                "output_id": output.get("output_id"),
            }

            # Log to disk
            log = _load_pr_log()
            log.append(result)
            _save_pr_log(log)

            return result

    async def create_pr_from_output_dict(self, output: dict) -> dict:
        """Create a real GitHub draft PR directly from an output dict."""
        if not self._token:
            return {"success": False, "error": "GITHUB_TOKEN not configured"}

        project = output.get("project", "")
        repo = self._repo(project)
        branch_name = output.get("suggested_branch", f"ai/improvement/{output.get('output_id', 'unknown')[:8]}")
        files = output.get("files", [])

        if not files:
            return {"success": False, "error": "No files to commit"}

        async with httpx.AsyncClient(timeout=30) as client:
            base_sha = await self._get_default_branch_sha(client, repo)
            if not base_sha:
                return {"success": False, "error": f"Cannot get main branch SHA for {repo}"}

            await self._create_branch(client, repo, branch_name, base_sha)

            files_committed = []
            for f in files:
                file_path = f.get("path", "")
                content = f.get("content") or f.get("description", "")
                if not content:
                    content = f"# AI-generated: {file_path}\n# {f.get('description', '')}"
                if not file_path:
                    continue
                ok = await self._upsert_file(
                    client, repo, branch_name, file_path,
                    content,
                    f"[AI OS] {f.get('description', f'Update {file_path}')}"
                )
                if ok:
                    files_committed.append(file_path)

            if not files_committed:
                return {"success": False, "error": "No files committed (content may be empty)"}

            pr_body = self._build_pr_body(output, files_committed)
            title = output.get("suggested_title", "[AI] Generated Improvement")
            pr_data = await self._create_draft_pr(client, repo, branch_name, "main", title, pr_body)

            if not pr_data:
                return {"success": False, "error": "Failed to create draft PR"}

            result = {
                "success": True,
                "pr_url": pr_data["html_url"],
                "pr_number": pr_data["number"],
                "pr_title": pr_data["title"],
                "branch": branch_name,
                "repo": repo,
                "files_committed": files_committed,
                "draft": True,
                "auto_merge": False,
                "created_at": datetime.utcnow().isoformat(),
                "output_id": output.get("output_id"),
            }
            log = _load_pr_log()
            log.append(result)
            _save_pr_log(log)
            return result

    def list_created_prs(self, limit: int = 20) -> list[dict]:
        return _load_pr_log()[-limit:]

    async def get_pr_status(self, repo: str, pr_number: int) -> dict:
        """Fetch live PR status from GitHub."""
        if not self._token:
            return {"error": "No token"}
        async with httpx.AsyncClient(timeout=10) as client:
            r = await client.get(
                f"{GITHUB_API}/repos/{repo}/pulls/{pr_number}",
                headers=self._headers(),
            )
            if r.status_code == 200:
                d = r.json()
                return {
                    "number": d["number"],
                    "title": d["title"],
                    "state": d["state"],
                    "draft": d["draft"],
                    "merged": d.get("merged", False),
                    "url": d["html_url"],
                    "created_at": d["created_at"],
                }
        return {"error": f"HTTP {r.status_code}"}
