/* MIFTEH OS — GitHub-native architecture
 * Dashboard data is served from /data/dashboard.json, generated by GitHub Actions AI workflows.
 * No backend server required.
 */
window.MIFTEH_DATA_URL = '/data/dashboard.json';

// GitHub Actions workflow dispatch links for manual triggers
window.MIFTEH_ACTIONS = {
  seo:       'https://github.com/Zakoosh/MIFTEH-AI-OS/actions/workflows/ai-seo-loop.yml',
  finance:   'https://github.com/Zakoosh/MIFTEH-AI-OS/actions/workflows/ai-finance-loop.yml',
  content:   'https://github.com/Zakoosh/MIFTEH-AI-OS/actions/workflows/ai-content-loop.yml',
  prs:       'https://github.com/Zakoosh/MIFTEH-AI-OS/actions/workflows/ai-pr-generator.yml',
  analytics: 'https://github.com/Zakoosh/MIFTEH-AI-OS/actions/workflows/ai-analytics-loop.yml',
  dashboard: 'https://github.com/Zakoosh/MIFTEH-AI-OS/actions/workflows/ai-dashboard-loop.yml',
};
