from __future__ import annotations
from datetime import datetime
from .models import OperationalOutput, OperationalPreview, OperationProject


class PreviewGenerator:
    def generate_apply_patch(self, output: OperationalOutput) -> dict:
        return {
            "output_id": output.id,
            "project": output.project if isinstance(output.project, str) else output.project.value,
            "output_type": output.output_type if isinstance(output.output_type, str) else output.output_type.value,
            "patch_count": len(output.patch_files),
            "files": [
                {
                    "path": p.get("file_path", ""),
                    "operation": p.get("operation", "create_or_update"),
                    "description": p.get("description", ""),
                    "content_size": len(str(p.get("content", ""))),
                }
                for p in output.patch_files
            ],
            "rollback_strategy": "snapshot_before_apply",
            "validation_required": True,
            "dry_run_supported": True,
            "generated_at": datetime.utcnow().isoformat(),
        }

    def render_html_preview(self, output: OperationalOutput, preview: OperationalPreview) -> str:
        project = output.project if isinstance(output.project, str) else output.project.value
        output_type = output.output_type if isinstance(output.output_type, str) else output.output_type.value
        files_html = "\n".join(
            f'<li><code>{p.get("file_path", "")}</code> — {p.get("description", "")}</li>'
            for p in output.patch_files
        )
        impact_html = "\n".join(
            f'<li><strong>{k}</strong>: {v}</li>'
            for k, v in (preview.estimated_impact or {}).items()
        )
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Preview: {output.title}</title>
  <style>
    body {{ font-family: -apple-system, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; }}
    .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }}
    .badge-low {{ background: #d1fae5; color: #065f46; }}
    .badge-medium {{ background: #fef3c7; color: #92400e; }}
    .badge-high {{ background: #fee2e2; color: #991b1b; }}
    .section {{ background: #f9fafb; border-radius: 8px; padding: 16px; margin: 16px 0; }}
    code {{ background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 13px; }}
    .warning {{ background: #fff7ed; border-left: 4px solid #f97316; padding: 12px 16px; }}
  </style>
</head>
<body>
  <h1>{output.title}</h1>
  <p>
    <span class="badge badge-{output.risk_level if isinstance(output.risk_level, str) else output.risk_level.value}">
      Risk: {output.risk_level if isinstance(output.risk_level, str) else output.risk_level.value}
    </span>
    &nbsp;
    <span class="badge" style="background:#dbeafe;color:#1e40af">
      {project} / {output_type}
    </span>
    &nbsp;
    {'<span class="badge" style="background:#ede9fe;color:#5b21b6">AI-Generated</span>' if output.ai_generated else '<span class="badge" style="background:#f3f4f6;color:#6b7280">Template</span>'}
  </p>
  <p>{output.description}</p>

  <div class="section">
    <h3>Files to Change ({len(output.patch_files)})</h3>
    <ul>{files_html}</ul>
  </div>

  <div class="section">
    <h3>Estimated Impact</h3>
    <ul>{impact_html}</ul>
  </div>

  <div class="warning">
    <strong>⚠ Preview Only</strong> — This output requires manual approval before apply. No changes have been made to the repository.
  </div>

  <div class="section">
    <h3>Preview Markdown</h3>
    <pre style="white-space: pre-wrap; font-size: 13px;">{preview.preview_markdown}</pre>
  </div>

  <p style="color: #9ca3af; font-size: 12px;">
    Generated by MIFTEH AI OS · {output.created_at} · Output ID: {output.id}
  </p>
</body>
</html>"""
