from __future__ import annotations
from typing import Any
from ..content_generator import ContentGenerator
from ..models import OperationalOutput, OperationalPreview, OutputType, OperationProject, RiskLevel

UX_PROPOSALS = [
    {
        "id": "onboarding_flow",
        "title": "Improved Onboarding Flow",
        "category": "user_journey",
        "priority": "critical",
        "current_problem": "High drop-off rate during KYC and account setup",
        "proposed_solution": "5-step progressive onboarding with progress indicator, skip options, and save-and-continue",
        "estimated_effort": "2 weeks",
        "expected_impact": "+25% onboarding completion rate",
        "components": ["OnboardingProgress", "KYCWizard", "RiskProfileQuiz"],
    },
    {
        "id": "dark_mode",
        "title": "Dark Mode Support",
        "category": "accessibility",
        "priority": "high",
        "current_problem": "No dark mode — causes eye strain for night traders",
        "proposed_solution": "System-aware dark mode with manual toggle, persisted in user preferences",
        "estimated_effort": "1 week",
        "expected_impact": "+15% evening session engagement",
        "components": ["ThemeProvider", "DarkModeToggle", "CSS custom properties"],
    },
    {
        "id": "rtl_arabic",
        "title": "Full RTL Arabic Support",
        "category": "localisation",
        "priority": "critical",
        "current_problem": "Arabic UI is partially RTL — charts and tables break in Arabic mode",
        "proposed_solution": "Full RTL CSS with dir=rtl, RTL-aware chart labels, Arabic number formatting",
        "estimated_effort": "3 weeks",
        "expected_impact": "+40% Arabic user retention",
        "components": ["RTLProvider", "ArabicNumberFormatter", "RTL chart labels"],
    },
    {
        "id": "empty_states",
        "title": "Improved Empty States",
        "category": "ux_polish",
        "priority": "medium",
        "current_problem": "Empty watchlist/portfolio shows blank page with no guidance",
        "proposed_solution": "Illustrated empty states with clear CTAs and sample data preview",
        "estimated_effort": "3 days",
        "expected_impact": "+20% feature discovery",
        "components": ["EmptyWatchlist", "EmptyPortfolio", "OnboardingCTA"],
    },
    {
        "id": "search_upgrade",
        "title": "Global Search Upgrade",
        "category": "navigation",
        "priority": "high",
        "current_problem": "Search only matches exact ticker symbols — misses company names",
        "proposed_solution": "Fuzzy search with company name, ticker, ISIN lookup + recent searches",
        "estimated_effort": "1 week",
        "expected_impact": "+30% symbol discovery rate",
        "components": ["GlobalSearch", "SearchResults", "RecentSearches"],
    },
]


class UXProposalGenerator:
    PROJECT = "fionera"

    def __init__(self):
        self._ai = ContentGenerator()

    def _render_proposal_doc(self, proposal: dict) -> str:
        return f"""# UX Proposal: {proposal['title']}

**Priority**: {proposal['priority'].upper()}
**Category**: {proposal['category']}
**Estimated Effort**: {proposal['estimated_effort']}
**Expected Impact**: {proposal['expected_impact']}

## Problem
{proposal['current_problem']}

## Proposed Solution
{proposal['proposed_solution']}

## Components Required
{chr(10).join(f'- {c}' for c in proposal['components'])}

## Acceptance Criteria
- [ ] Works in RTL (Arabic) mode
- [ ] Mobile-responsive (320px+)
- [ ] Accessible (WCAG AA)
- [ ] Dark mode compatible
- [ ] i18n keys added for all strings

---
*Generated by MIFTEH AI OS — Requires design review before implementation*
"""

    def _render_empty_state_component(self) -> str:
        return """import { PlusCircle } from 'lucide-react';

interface EmptyStateProps {
  icon: React.ReactNode;
  title: string;
  description: string;
  ctaText: string;
  onCta: () => void;
}

export function EmptyState({ icon, title, description, ctaText, onCta }: EmptyStateProps) {
  return (
    <div className="empty-state flex flex-col items-center justify-center py-16 px-4 text-center">
      <div className="mb-4 p-4 bg-gray-50 rounded-full text-gray-400">{icon}</div>
      <h3 className="text-lg font-semibold text-gray-800 mb-2">{title}</h3>
      <p className="text-gray-500 text-sm max-w-xs mb-6">{description}</p>
      <button onClick={onCta} className="flex items-center gap-2 bg-blue-600 text-white px-5 py-2.5 rounded-xl font-medium hover:bg-blue-700 transition-colors">
        <PlusCircle size={16} />{ctaText}
      </button>
    </div>
  );
}

export function EmptyWatchlist({ onAddSymbol }: { onAddSymbol: () => void }) {
  return <EmptyState icon={<span className="text-3xl">📊</span>} title="Your watchlist is empty" description="Add stocks, ETFs, or crypto to track prices and get alerts" ctaText="Add your first symbol" onCta={onAddSymbol} />;
}

export function EmptyPortfolio({ onAddHolding }: { onAddHolding: () => void }) {
  return <EmptyState icon={<span className="text-3xl">💼</span>} title="No holdings yet" description="Add your positions to track performance and get insights" ctaText="Add a holding" onCta={onAddHolding} />;
}
"""

    def _render_global_search(self) -> str:
        return """'use client';
import { useState, useRef, useEffect } from 'react';
import { Search, Clock, TrendingUp } from 'lucide-react';
import { useRouter } from 'next/navigation';

export function GlobalSearch() {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [recent, setRecent] = useState<string[]>([]);
  const [open, setOpen] = useState(false);
  const router = useRouter();
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const saved = localStorage.getItem('fionera_recent_searches');
    if (saved) setRecent(JSON.parse(saved));
  }, []);

  useEffect(() => {
    if (!query || query.length < 2) { setResults([]); return; }
    const timer = setTimeout(() => {
      fetch(`/api/search?q=${encodeURIComponent(query)}&limit=8`)
        .then(r => r.json())
        .then(data => setResults(data.results));
    }, 200);
    return () => clearTimeout(timer);
  }, [query]);

  const handleSelect = (symbol: string) => {
    const updated = [symbol, ...recent.filter(r => r !== symbol)].slice(0, 5);
    setRecent(updated);
    localStorage.setItem('fionera_recent_searches', JSON.stringify(updated));
    router.push(`/markets/${symbol.toLowerCase()}`);
    setOpen(false);
    setQuery('');
  };

  return (
    <div className="global-search relative">
      <div className="search-input flex items-center gap-2 px-3 py-2 border rounded-xl bg-gray-50 focus-within:ring-2 ring-blue-500">
        <Search size={16} className="text-gray-400" />
        <input ref={inputRef} placeholder="Search symbols, companies..." value={query} onChange={e => setQuery(e.target.value)} onFocus={() => setOpen(true)} className="flex-1 bg-transparent outline-none text-sm" />
        {query && <button onClick={() => setQuery('')} className="text-gray-400 hover:text-gray-600">×</button>}
      </div>
      {open && (
        <div className="search-dropdown absolute top-full left-0 right-0 mt-1 bg-white border rounded-xl shadow-xl z-50 overflow-hidden">
          {results.length > 0 ? (
            <ul>{results.map((r: any) => (<li key={r.symbol} onClick={() => handleSelect(r.symbol)} className="flex items-center gap-3 px-4 py-3 hover:bg-gray-50 cursor-pointer"><TrendingUp size={14} className="text-gray-400" /><div><p className="font-medium text-sm">{r.symbol}</p><p className="text-xs text-gray-500">{r.name}</p></div><span className="ml-auto text-sm font-mono">{r.price}</span></li>))}</ul>
          ) : recent.length > 0 && !query ? (
            <div className="px-4 py-2"><p className="text-xs text-gray-400 mb-2 flex items-center gap-1"><Clock size={12}/>Recent</p>{recent.map(r => (<button key={r} onClick={() => handleSelect(r)} className="block w-full text-left px-2 py-1.5 text-sm hover:bg-gray-50 rounded">{r}</button>))}</div>
          ) : query.length >= 2 ? (
            <p className="px-4 py-6 text-center text-sm text-gray-400">No results for "{query}"</p>
          ) : null}
        </div>
      )}
    </div>
  );
}
"""

    async def generate_ux_proposals(self, priority_filter: str | None = None, use_ai: bool = False) -> tuple[OperationalOutput, OperationalPreview]:
        proposals = UX_PROPOSALS if not priority_filter else [p for p in UX_PROPOSALS if p["priority"] == priority_filter]
        ai_generated = False
        cost, tokens = 0.0, 0

        if use_ai and self._ai.is_ai_available():
            result = await self._ai.generate(
                prompt="Given a MENA-focused investment platform (Fionera), suggest 2 UX improvements that would specifically improve trust and engagement for first-time investors in the GCC region. Consider: local payment methods, Sharia compliance indicators, Arabic language support. Return JSON: [{title, problem, solution, priority, expected_impact}]",
                system_prompt="You are a UX researcher specialising in fintech for emerging markets.",
                max_tokens=350,
            )
            if result.get("success"):
                ai_generated = True
                cost = result.get("cost_usd", 0)
                tokens = result.get("total_tokens", 0)

        patch_files = [
            {"file_path": "src/components/EmptyStates.tsx", "operation": "create", "content": self._render_empty_state_component(), "description": "Empty state components for watchlist and portfolio"},
            {"file_path": "src/components/GlobalSearch.tsx", "operation": "create", "content": self._render_global_search(), "description": "Global symbol search with fuzzy matching and history"},
        ]
        for p in proposals:
            patch_files.append({
                "file_path": f"docs/ux-proposals/{p['id']}.md",
                "operation": "create",
                "content": self._render_proposal_doc(p),
                "description": f"UX proposal document: {p['title']}",
            })

        output = OperationalOutput(
            project=OperationProject.fionera,
            output_type=OutputType.ux_proposal,
            title=f"UX Proposals — {len(proposals)} Improvements",
            description=f"UX improvement proposals: {', '.join(p['title'] for p in proposals[:3])}{'...' if len(proposals) > 3 else ''}",
            content={"proposals": proposals, "total_critical": len([p for p in proposals if p["priority"] == "critical"])},
            patch_files=patch_files,
            risk_level=RiskLevel.low,
            ai_generated=ai_generated,
            cost_usd=cost,
            tokens_used=tokens,
        )
        preview = OperationalPreview(
            output_id=output.id,
            project=OperationProject.fionera,
            preview_markdown="# UX Proposals\n\n" + "\n\n".join(f"## {p['title']} [{p['priority'].upper()}]\n**Problem**: {p['current_problem']}\n**Solution**: {p['proposed_solution']}\n**Impact**: {p['expected_impact']}" for p in proposals),
            diff_summary=f"Creates {len(patch_files)} UX proposal files and components",
            files_changed=[p["file_path"] for p in patch_files],
            estimated_impact={"onboarding_completion": "+25%", "arabic_retention": "+40%", "search_success": "+30%"},
        )
        output.preview_id = preview.id
        return output, preview
