"""
MIFTEH OS — Draft PR Generator
Reads latest AI outputs and creates draft PRs in target repositories.
Requires: GH_PAT secret with repo access to Zakoosh/Yallaplays, Zakoosh/fionera, Zakoosh/mifteh-main-site
"""
import base64
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from ai_client import now_iso, today_str


def gh(method, path, payload=None, token=None):
    token = token or os.environ.get("GH_PAT") or os.environ.get("GITHUB_TOKEN", "")
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        data=json.dumps(payload).encode() if payload else None,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "MIFTEH-AI-OS/2.0",
            "Content-Type": "application/json",
        },
        method=method,
    )
    try:
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read()), r.getcode()
    except urllib.error.HTTPError as e:
        body = e.read().decode()[:300]
        print(f"[prs] {method} {path} => {e.code}: {body}")
        return None, e.code


def get_default_branch(owner, repo, token):
    data, _ = gh("GET", f"/repos/{owner}/{repo}", token=token)
    return (data or {}).get("default_branch", "main")


def get_branch_sha(owner, repo, branch, token):
    data, _ = gh("GET", f"/repos/{owner}/{repo}/git/refs/heads/{branch}", token=token)
    return ((data or {}).get("object", {})).get("sha")


def ensure_branch(owner, repo, branch, from_sha, token):
    _, code = gh("POST", f"/repos/{owner}/{repo}/git/refs", {"ref": f"refs/heads/{branch}", "sha": from_sha}, token=token)
    return code in (200, 201, 422)  # 422 = branch already exists


def put_file(owner, repo, branch, path, content_str, message, token):
    existing, _ = gh("GET", f"/repos/{owner}/{repo}/contents/{path}?ref={branch}", token=token)
    payload = {
        "message": message,
        "content": base64.b64encode(content_str.encode()).decode(),
        "branch": branch,
    }
    if isinstance(existing, dict) and existing.get("sha"):
        payload["sha"] = existing["sha"]
    _, code = gh("PUT", f"/repos/{owner}/{repo}/contents/{path}", payload, token=token)
    return code in (200, 201)


def create_pr(owner, repo, branch, base, title, body, token):
    data, code = gh("POST", f"/repos/{owner}/{repo}/pulls", {
        "title": title,
        "body": body,
        "head": branch,
        "base": base,
        "draft": True,
    }, token=token)
    return data, code


def load_latest(project, op_type):
    p = Path(f"outputs/{project}/{op_type}/latest.json")
    return json.loads(p.read_text()) if p.exists() else None


def already_created(project, branch):
    f = Path(f"memory/prs_{project}.json")
    if not f.exists():
        return False
    return any(p.get("branch") == branch for p in json.loads(f.read_text()))


def record_pr(project, pr_info):
    f = Path(f"memory/prs_{project}.json")
    records = json.loads(f.read_text()) if f.exists() else []
    records.append(pr_info)
    f.parent.mkdir(exist_ok=True)
    f.write_text(json.dumps(records[-100:], indent=2))


def format_md(output):
    content_str = json.dumps(output.get("content", {}), indent=2, ensure_ascii=False)
    if len(content_str) > 8000:
        content_str = content_str[:8000] + "\n... (truncated)"
    mode = "🤖 AI-generated" if output.get("ai_generated") else "📝 Template"
    return "\n".join([
        f"# {output.get('title', 'AI Suggestion')}",
        "",
        f"**Generated:** {output.get('generated_at', '')}  ",
        f"**Mode:** {mode} ({output.get('ai_model', 'unknown')})  ",
        f"**Tokens:** {output.get('tokens_used', 0):,}  ",
        "",
        "---",
        "",
        "## Generated Content",
        "",
        "```json",
        content_str,
        "```",
        "",
        "---",
        "",
        "> ⚠️ **Draft PR — human review required before merge.**  ",
        "> 🤖 Generated by [MIFTEH AI OS](https://miftehos.com)",
    ])


def format_pr_body(project, output):
    mode = "🤖 Real AI generation" if output.get("ai_generated") else "📝 Template fallback"
    return f"""## {output.get('title', 'AI Suggestion')}

### Summary
- AI-generated optimization suggestions for **{project}**
- Generated: `{output.get("generated_at", "")}`
- Mode: {mode}

### Files Added
- `ai-suggestions/` — AI optimization report (markdown + JSON)

### Review Checklist
- [ ] Review AI suggestions for accuracy and appropriateness
- [ ] Verify suggestions align with project goals
- [ ] Apply relevant improvements manually to the codebase
- [ ] Close or merge after completing review

---
> ⚠️ **Draft PR — do not merge without review**
> 🤖 Generated by [MIFTEH AI OS](https://miftehos.com)
> Never auto-merged · Preview-first · Human approval required"""


def process(project, repo_full, op_type, token):
    output = load_latest(project, op_type)
    if not output:
        print(f"[prs] No output for {project}/{op_type} — skipping")
        return None

    branch = output.get("suggested_branch", f"ai/{project[:2]}-{op_type}-{today_str()}")

    if already_created(project, branch):
        print(f"[prs] PR for {branch} already exists — skipping")
        return None

    owner, repo = repo_full.split("/", 1)
    default = get_default_branch(owner, repo, token)
    sha = get_branch_sha(owner, repo, default, token)
    if not sha:
        print(f"[prs] Cannot get SHA for {repo_full} — skipping")
        return None

    ensure_branch(owner, repo, branch, sha, token)

    date = today_str()
    put_file(owner, repo, branch, f"ai-suggestions/{op_type}-{date}.md",
             format_md(output), f"AI: {output.get('title', op_type)} [{date}]", token)
    put_file(owner, repo, branch, f"ai-suggestions/{op_type}-{date}.json",
             json.dumps(output, indent=2, ensure_ascii=False),
             f"AI: raw data for {op_type} [{date}]", token)

    title = output.get("title", f"AI: {op_type.replace('_', ' ').title()} — {date}")
    pr_data, code = create_pr(owner, repo, branch, default, title, format_pr_body(project, output), token)

    if code not in (200, 201):
        print(f"[prs] PR creation failed for {repo_full} ({code})")
        return None

    result = {
        "project": project,
        "repo": repo_full,
        "branch": branch,
        "pr_number": (pr_data or {}).get("number"),
        "pr_url": (pr_data or {}).get("html_url"),
        "pr_title": title,
        "created_at": now_iso(),
        "ai_generated": output.get("ai_generated", False),
        "operation_type": op_type,
        "files_committed": [f"ai-suggestions/{op_type}-{date}.md", f"ai-suggestions/{op_type}-{date}.json"],
    }
    record_pr(project, result)
    print(f"[prs] Created PR #{result['pr_number']} in {repo_full}: {result['pr_url']}")
    return result


def main():
    token = os.environ.get("GH_PAT", "")
    if not token:
        print("[prs] GH_PAT not set — skipping PR creation (set secret in GitHub repo settings)")
        return []

    targets = {
        "yallaplays": (os.environ.get("GITHUB_REPO_YALLAPLAYS", "Zakoosh/Yallaplays"), "seo"),
        "fionera":    (os.environ.get("GITHUB_REPO_FIONERA",    "Zakoosh/fionera"),    "insights"),
        "mifteh":     (os.environ.get("GITHUB_REPO_MIFTEH",     "Zakoosh/mifteh-main-site"), "seo"),
    }

    results = []
    for project, (repo_full, op_type) in targets.items():
        r = process(project, repo_full, op_type, token)
        if r:
            results.append(r)

    # Append to global PR log
    all_prs_file = Path("memory/all_prs.json")
    all_prs = json.loads(all_prs_file.read_text()) if all_prs_file.exists() else []
    all_prs.extend(results)
    all_prs_file.parent.mkdir(exist_ok=True)
    all_prs_file.write_text(json.dumps(all_prs[-100:], indent=2))

    print(f"[prs] Created {len(results)} draft PR(s)")
    return results


if __name__ == "__main__":
    main()
